### ISSUE TITLE
making dev env better for grafana work

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#23]
1. is it just me or does ./setup_dev.sh not cause grafana to be recompiled? this is interesting since it does update the code, runs npm install and grunt, but doesn't actually seem to build grafana, causing `/go/bin/grafana` to be whatever the image was built with initially (similar for raintank-metric actually, code gets updated but nothing seems to be done with it)
2. i'm trying to make the env a bit better for grafana dev work. I'm thinking perhaps create a grafana-dev supervisor profile that uses `bra run` to auto-recompile-and-run on code change, and also i would have to make sure it always run `godep restore` before building.  any thoughts, comments, experiences? 

I find it a big win that I can just edit my grafana codebase on my laptop/host in my regular environment, have `raintank_code/grafana` be a symlink to it, and be able to test it in the dev stack very easily. but i've always manually compiled so far and want to fix that :)

@torkelo @woodsaj @ctdk @mattttt are all you guys still using the dev stack or have you found another way i'm not aware of :)

**Comment by torkelo** [comment]
yea, I could not get setup_dev.sh to work, the raintank_code/grafana dir just ended up empty (single data dir in it). Could not figure out what was wrong :( 

Now that we do not use this docker env for staging or prod we can simplify it for dev work. For example remove supervisor from grafana container and just run "bra run". 

something like this:

``` dockerfile
FROM raintank/nodejs

RUN apt-get update && apt-get -y install supervisor libfontconfig1 libfreetype6 libjpeg8 libstdc++6

# add script, but don't run it. for now this is only used in dev stack
ADD create-influxdb-dev-datasource.sh /tmp/create-influxdb-dev-datasource.sh
RUN chmod +x /tmp/create-influxdb-dev-datasource.sh

ENV GOPATH /go

RUN curl -SL https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz \
    | tar -xzC /usr/local

RUN mkdir -p /go/src/github.com/grafana
RUN mkdir -p /go/src/github.com/raintank
RUN ln -s /go/src/github.com/raintank/grafana /go/src/github.com/grafana/grafana

ENV GOPATH /go
ENV PATH $PATH:/usr/local/go/bin:$GOPATH/bin
RUN go get github.com/raintank/grafana
RUN go get github.com/Unknwon/bra
RUN go get github.com/tools/godep
WORKDIR /go/src/github.com/raintank/grafana
RUN npm install && npm install -g grunt-cli && grunt build

EXPOSE 80
EXPOSE 443

RUN mkdir -p /var/log/raintank
COPY conf/custom.ini /etc/grafana/custom.ini

# makes builds 1000% faster when sqlite3 is installed (does not need to recompiled every build)
RUN go install -v gitthub.com/mattn/go-sqlite3
RUN godep restore
CMD ["bra run"]
```

**Comment by torkelo** [comment]
that CMD command might not be correct, think it is `CMD ["bra", "run"]` or something

**Comment by Dieterbe** [comment]
> yea, I could not get setup_dev.sh to work, the raintank_code/grafana dir just ended up empty (single data dir in it). Could not figure out what was wrong :( 

this was probably due to a bug I caused and recently fixed: 06952fc49d06e9737eeae79d27400377a7724c2e (also: apologies for mixed indentation, let's standardize on tabs like gofmt.)

**Comment by woodsaj** [comment]
The reason that the go binary doesnt get updated when a new stack is launched is because supervisorctl  executes /go/bin/grafana, which only lives in the docker image, not in the linked raintank-code/grafana dir.  

So to improve things, we can either change the supervisord conf to launch $GOPATH/src/github.com/grafana/grafana/grafana or change it to just launch bra instead.

**Comment by Dieterbe** [comment]
OK. we all agree that there's no reason to spend effort on maintaining a raintank-grafana production docker image, right?

**Comment by Dieterbe** [comment]
@torkelo I notice your docker image (also our current image) uses `github.com/raintank/grafana` not `github.com/grafana/grafana`. even if both contain the same data (via symlink), isn't this a problem? i seem to recall we recommend `grafana/grafana` over `raintank/grafana` for a good reason but I forgot why. something with import paths? btw i just saw a [data race](https://gist.github.com/Dieterbe/2964386feba85b544d95) which solved itself when i compiled in `grafana/grafana` but i can't really explain why.

**Comment by Dieterbe** [comment]
@torkelo fyi i decided to run bra under supervisord so that we can always restart bra without issues. if bra was the init processes the container exits when the process stops.

**Comment by torkelo** [comment]
Ok, I forgot about that :)
