### ISSUE TITLE
how to automatically have alerting dashboard available in dev stack?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#27]
right now when i run a devstack i have to manually import https://github.com/raintank/grafana/blob/master/alerting.json into grafana.
it would be nice if this dashboard was already available somehow.
obviously I can't just commit a change to raintank/grafana that puts the dashboard file with the other dashboard, because then it would end up amongst the live dashboards too.
one of the devstack scripts could copy it but that's kind of clunky too because then it dirties the workspace and you can't easily commit changes.

i was wondering if there was perhaps a way certain dashboards only available to the "root admin" or something. perhaps by putting them in a different directory.
but i couldn't figure out how that would be done. see also https://github.com/grafana/grafana/issues/2302

**Comment by Dieterbe** [comment]
@torkelo any idea?

**Comment by torkelo** [comment]
why is this json in repo root? what does it do? Why is it not with the other raintank json dashboards?

**Comment by Dieterbe** [comment]
it's in repo root because i don't know what's the right place to put it.
it provides insights on alerting performance, so it is useful to people running grafana (admins) and wanting to get insights in the performance of the alerting feature.  however, it is not necessarily useful to regular users of grafana, and it definitely should not be exposed to users of litmus. (unless those users are admins)

**Comment by torkelo** [comment]
maybe it should be in the chef files and updated via the HTTP api on deploys?

**Comment by Dieterbe** [comment]
I also need the dash while developing. So in devstack.

**Comment by torkelo** [comment]
ah, so maybe it should be in this repo, and not in the root source repo?

**Comment by Dieterbe** [comment]
let me paraphrase the requirements:
1. should be available for use in devstack
2. want to be able to make changes to it and commit them
3. would also be useful for grafana "master admins" who run a grafana instance (in prod) and use influxdb for grafana's telemetry

Your last suggestion would work, but the dev stack couldn't just copy the dashboard into the dashboards dir, because then it wouldn't be easy to commit changes back into the devstack repo.
If grafana supports loading dashboards from multiple directories, then we could make it work by volume-mounting a devstack's dashboard directory.
this however still doesn't help with the 3rd case. although those people could just import the dashboard from the devstack since it's publically provided anyway.

I was thinking more along the lines of having grafana support a special dashboards directory that has dashboards that are only visible to the site admin. this would solve all 3 goals in 1 shot.
have you perhaps thought of a sort of permission system where people only see certain dashboards based on their role/privilege?
the other catch is that it's only designed for influxdb so it would only work if you had an influxdb datasource called 'influxdb'. anyway perhaps this too far off.

**Comment by torkelo** [comment]
@Dieterbe ah, now I understand the case better. Sorry for being slow. 

I like the idea of "admin" dashboards that can show internal grafana stats. But it would have to be data source agnostic (or maybe exist in different versions).

**Comment by Dieterbe** [comment]
so how do you suggest we proceed?

**Comment by torkelo** [comment]
not sure, just anywhere but repo root :) 

Maybe put them in public/raintank/dashboards/admin/alerting.json

**Comment by Dieterbe** [comment]
but we don't have admin-specific dashboards yet, so would that even work?

**Comment by torkelo** [comment]
well, no, we do no have anything like admin dashboards, or admin data sources. 

just a better place then repo root.

**Comment by Dieterbe** [comment]
@torkelo i wish we had a solution for this. i'm getting a bit tired of manually importing json files into grafana every time i run devstack, and exporting to json files whenever i make a change :1234: 
i could automatically import them into the database, and run a script that polls the db every few seconds and saves it to the file but that is quite clunky too.

**Comment by woodsaj** [comment]
The dashboards you are referring to are not a part of grafana, they are a part of your telemetry system for monitoring grafana, which could use Influx, graphite or any other TSDB, or even be in a completely separate system (Datadog).

Trying to build them into grafana is the wrong idea IMHO.  Instead you should leverage Grafana's API for deploying the dashboards. You can also use the API for periodically polling the dashboards for changes. 

Though to think you should just treat the dashboards like any other code,  Write, test, commit, deploy.
Complaining that you have to keep exporting your json files when you make changes is like complaining that your Orchestration software (Chef, Puppet) doesnt update your recipes when you make live changes to a server.

I think you should just keep your dashboards in separate Git repo and write a small script for publishing them to a grafana server via the API.

**Comment by torkelo** [comment]
agree with @woodsaj on this one :)

**Comment by Dieterbe** [comment]
> Though to think you should just treat the dashboards like any other code, Write, test, commit, deploy.

not sure what you meant with this. but i presume you meant "try to just treat.. " ?

while i agree that my proposed solution is a bit invasive and we should aim for a simple solution that doesn't add too much (ideally none) custom code to grafana, I don't agree with this:

> Complaining that you have to keep exporting your json files when you make changes is like complaining that your Orchestration software (Chef, Puppet) doesnt update your recipes when you make live changes to a server.

the big difference is that grafana is the only sensible way to make changes to a grafana dashboard.  editing the json files by hand is not the primary (or even a sensible) way to change dashboards, in contrast to your orchestration example where editing the recipes is the best way.

**Comment by torkelo** [comment]
@Dieterbe but you can build the dashboard in grafana and export it, and then have an automated system that pushes via the HTTP api when you spin up a new instance

**Comment by Dieterbe** [comment]
yeah that seems to be the simplest solution. and just export it whenever i change it

**Comment by Dieterbe** [comment]
some people were asking for the same thing https://github.com/grafana/grafana/issues/2567
so for posterity, once that's implemented, we'll be able to address this more elegantly.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/commit/09b3433e3201970f109a8b01e5e3ebe52513f0a8
