### ISSUE TITLE
cassandra taking 300% CPU in idle dev stack

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#29]
earlier i did some high load scenarios and was getting errors like https://gist.github.com/Dieterbe/ed34b92ee6bfc7289d05

however i've started a fresh stack with very little load and i still see high (100~300%) cpu usage for cassandra. is it possible that somehow consequences of previous runs are still visible in the current stack?

i'm also seeing errors like https://gist.github.com/Dieterbe/d5c6e0706a038e2f6270

**Comment by Dieterbe** [comment]
FWIW i ended up rebooting my computer and running ./build.sh and ./setup_dev.sh again and that "resolved" it.
@woodsaj any thoughts? if not, we can just close this.

**Comment by woodsaj** [comment]
allow of these look like connectivity issues between your docker containers.

**Comment by Dieterbe** [comment]
k, will close it for now then. not really actionable.
