### ISSUE TITLE
make host names nice things

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#30]
![annoy](https://cloud.githubusercontent.com/assets/20774/9429336/a21b1e90-49cc-11e5-99a2-420eb68da470.png)
randomized hostnames are too annoying.
especially when building dashboards, good luck making the dashboard work next docker run..

i see how docker-compose has `container_name` option, but that's just the docker container name.
`docker run` has a `-h` flag for host name but that's not useable through docker-compose :?

**Comment by woodsaj** [comment]
https://docs.docker.com/compose/yml/

you can just add `hostname` field to your docker compose yaml (fig.yaml)

**Comment by Dieterbe** [comment]
patch is in tank, want to keep this open until it's in master (or in a branch that is guaranteed to be merged to master soon)
