### ISSUE TITLE
failed to query for events

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#34]
added an endpoint, go to litmus events.
shows an error : 

```
Problem!
Failed to query events
```

in grafana log the following shows:

```
2015/09/09 11:22:03 ESC[1;31m[event.go:26 GetEvents()] [E] Failed to query events: record not foundESC[0m
2015/09/09 11:22:03 ESC[1;32m[I] ESC[1;36mCompleted /api/events 500 Internal Server Error in 3.275729msESC[0mESC[0m
```

**Comment by Dieterbe** [comment]
hmm this might be due to the bulkindexer i'm trying out, though i think i've gotten this in the past as well.
i'll see if i can reproduce with the elasticsearch worker from master

**Comment by woodsaj** [comment]
This is typically because no events have been indexed. The index is only created when the first document is received.

Is the nsq_probe_events_to_elastic running?

**Comment by Dieterbe** [comment]
yes nsq_probe_events_to_elastic is running but the output is only 

```
2015/09/09 16:57:15 INF    1 [probe_events/elasticsearch] (nsqd:4150) connecting to nsqd
2015/09/09 16:57:15 connected to nsqd
2015/09/09 16:57:15 INFO starting listener for http/debug on :6060

```

also seeing it with nsq_probe_events_to_elastic compiled from master branch.

but i suspect something is wrong with the collector. see also #35
