### ISSUE TITLE
Grafana build failure

### ISSUE THREAD

**Issue by mflintoff** [raintank/raintank-docker#36]
Did a git checkout and tried to run ./build_all.sh script. It failed while building the grafana Dockerfile:

Step 13 : RUN godep restore
 ---> Running in 14071b951029
 ---> 7becf68026ba
Removing intermediate container 14071b951029
Step 14 : RUN go build .
 ---> Running in a873be45ff44
../../grafana/grafana/pkg/services/metricpublisher/metricpublisher.go:11:2: cannot find package "github.com/raintank/raintank-metric/msg" in any of:
        /usr/local/go/src/github.com/raintank/raintank-metric/msg (from $GOROOT)
        /go/src/github.com/raintank/raintank-metric/msg (from $GOPATH)
The command '/bin/sh -c go build .' returned a non-zero code: 1
failed building grafana. stopping.

**Comment by Dieterbe** [comment]
i think i caused this. will have a look.

**Comment by dahendel** [comment]
I have the same issue. I tried adding a line in the Dockerfile to go get github.com/raintank/raintank-metric/msg which is what I did locally to get it to compile, but that did not work either.

**Comment by Dieterbe** [comment]
should be fixed now, can you confirm?

**Comment by Dieterbe** [comment]
tested and works for me. please reopen if you get the error again.
