### ISSUE TITLE
better running of graphite-api

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#39]
i know in devstack we switched to gunicorn to use multiple CPU's
but i often have to switch start_graphite.py to use app.run so that i can see errors in the log, but then i have worse performance (presumably, didn't check).

i know in chef stack we've recently changed how graphite-api runs so we have good performance and also error logs. but not sure about the specifics, @woodsaj can you do the same thing for dev stack?

**Comment by woodsaj** [comment]
You can get errors out of gunicorn by changing the log settings in
/etc/graphite-api.yaml.

Just look at the conf on a Dev node.
