### ISSUE TITLE
how to get WP working in new dev stack?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#60]
we just merged in grafana3 + WP app instead of the deprecated raintank fork that had WP (litmus) embedded in grafana.
but how to get WP working in the new stack?

@woodsaj could you please answer the following questions:

1) we need to modify raintank_code/plugins/worldping-app/dist/plugin.json and change the url from ""https://worldping-api.raintank.io/api"" to "http://worldping/api" <-- can we make this so that we don't need to make manual adjustments?

2) is there a way to trigger enabling the app, importing the dashboards and such, or is that still a manual step? should we first manually get an api key from http://localhost:3000/org/apikeys ?

3) create-dev-datasource.sh used to have a neat trick where it would automatically insert a known api key into the mysql db. why was this removed? this was more convenient than doing it manually IMHO

4) because of 3) launch_dev_collector.sh can now no longer authenticate itself (as far as i can see) since we now use `"Authorization: Bearer changeme"` instead of the auto-created api keys. what should we change this too? maybe `admin:admin` instead of a key?

5) how does the probe authenticate itself? in /opt/raintank/raintank-collector/etc/raintank.json it still says `"apiKey": "changeme"`

**Comment by woodsaj** [comment]
1) The plugin needs to point to worldping-api.raintank.io else it wont work when users download it.  So the only option is to somehow transparently proxy requests sent to https://worldping-api.raintank.io to http://worldping/.   Your guess is as good as mine on how that could be done.

2) You have to manually enable the app.  http://localhost:3000/org/apikeys is just for apiKeys to on the local grafana install. Those keys have nothing to do with worldping.  To enable worldping you still need to get a key from grafana.net or use the adminKey (see item 4)

3) worldping-api does not store api keys.  It simple validates keys against grafana.net (unless it is the adminKey, see below)
https://github.com/raintank/worldping-api/blob/master/pkg/middleware/middleware.go#L50

4) worldping-api has an "adminKey" defined in the configfile. If this key is used then it is granted admin role on Org 1, and also has the "grafanaAdmin" flag.  The default adminKey defined in the config is "changme"

5) using the adminKey, which by default is "changeme"

**Comment by woodsaj** [comment]
re 1), i have added a proxy container to the stack that now proxies requests for https://worldping-api.raintank.io to http://worldpingapi (the worldpingApi container)

So for me (and i have tested on a fresh install) the stack is working 100%.  
- start the stack `./launch_dev.sh`
- log into grafana `http://localhost:3000`
- enable the worldping-app, using "changeme" as the apiKey
- add an endpoint

**Comment by Dieterbe** [comment]
bleh, i keep getting 500's from grafana as soon as i try to use WP. tried debug mode, not getting anything more. not seeing requests in worldping-api.

```
2016/04/12 19:57:34 [I] Completed 172.17.0.1 admin "GET /api/monitor_types HTTP/1.1" 500 Internal Server Error 0 bytes in 171423us
2016/04/12 19:57:34 [I] Completed 172.17.0.1 admin "GET /api/collectors HTTP/1.1" 500 Internal Server Error 0 bytes in 171284us
```

trying to use the datasource, where grafana calls `http://localhost:3000/api/plugin-proxy/raintank-worldping-app/api/graphite/metrics/find/?query=*` also results in 500's and those aren't even showing up in the logs.
i'll try to grab you or torkel/daniel tomorrow to pair on this.

**Comment by woodsaj** [comment]
issues were due to local modifications to the worldping-app plugin.json
