### ISSUE TITLE
while Recompile backend on source change, i got an errors..

### ISSUE THREAD

**Issue by yuvaraj951** [raintank/raintank-docker#64]
No command 'bra' found, did you mean:
 Command 'br' from package 'bottlerocket' (universe)
 Command 'ra' from package 'argus-client' (universe)
 Command 'brag' from package 'brag' (universe)
 Command 'bar' from package 'bar' (universe)
 Command 'bwa' from package 'bwa' (universe)
 Command 'bro' from package 'bro' (universe)
 Command 'ara' from package 'ara' (universe)
bra: command not found
please help me out!!!!

**Comment by Dieterbe** [comment]
I believe this has been fixed when we switched to the new grafana3 + plugin setup.

**Comment by dtodoro3** [comment]
Hello, I have the same error and I am with version 4.3.0

**Comment by dtodoro3** [comment]
Do you have any fix for this problem?
