### ISSUE TITLE
rabbitmq image doesn't run

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#8]
```
dieter@dieter-m6800 raintank-docker  docker run raintank/rabbitmq /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.0/sbin/rabbitmq-server
/docker-entrypoint.sh: line 9: /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.0/sbin/rabbitmq-server: No such file or directory
dieter@dieter-m6800 raintank-docker  docker run raintank/rabbitmq ls -alh /usr/lib/rabbitmq/lib/
total 12K
drwxr-xr-x 3 root root 4.0K Apr 30 05:56 .
drwxr-xr-x 4 root root 4.0K Apr 30 05:56 ..
drwxr-xr-x 6 root root 4.0K Apr 30 05:56 rabbitmq_server-3.5.1
```

we can have two approaches:
- update the fig-dev.yaml accordingly, perhaps by running something like `/usr/lib/rabbitmq/lib/rabbitmq_server-3.*/sbin/rabbitmq-server`, or updating the version everytime our stack breaks because the version updates
- pin the rabbitmq version to a specific version, and do more controlled, less frequent updates and tests?

i think i prefer the second option.

**Comment by woodsaj** [comment]
https://github.com/raintank/raintank-docker/blob/master/fig-dev.yaml#L14
the `command` was added to the docker-compose yaml because of a previous bug in the rabbitmq image.

This command is no longer required and can be removed.
