### ISSUE TITLE
unable to query MT through worldping datasource

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#80]
so tsdb-gw listens on `/graphite/`, not `/api/graphite`, at first i was struggling for a while with the nginx proxy container but then found out that the culprit is probably worldping-app which seems to have this issue adressed since https://github.com/raintank/worldping-app/commit/be04ed14c6b22a87d5f6d4c797de957c07feb1f5

however, when loading in this code (which needed #79), i was still seeing the requests going to `http://localhost:3000/api/plugin-proxy/raintank-worldping-app/api/graphite/metrics/find/?query=*`

which results in this (from nginx log):

```
172.19.0.23 - - [08/Sep/2016:17:56:38 +0000] "GET /graphite/metrics/find?query=* HTTP/1.1" 500 1508 "http://localhost:3000/dashboard/new?panelId=1&fullscreen&edit" "Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0" "172.19.0.1"
```

i then tried : 

```
index 0eda4c9..9809daa 100644
--- a/dist/components/config/config.js
+++ b/dist/components/config/config.js
@@ -158,7 +158,7 @@ System.register(['./config.html!text', 'lodash'], function (_export, _context) {
                 var graphite = {
                   name: 'raintank',
                   type: 'graphite',
-                  url: 'api/plugin-proxy/raintank-worldping-app/api/graphite',
+                  url: 'api/plugin-proxy/raintank-worldping-app/graphite',
                   access: 'direct',
                   jsonData: {}
                 };

```

which causes the requests to go to `http://localhost:3000/api/plugin-proxy/raintank-worldping-app/graphite/metrics/find/?query=*` instead, but that gives me 404 page not found.

**Comment by woodsaj** [comment]
make sure you have the latest version of tsdb-gw and latest version of worldping-app

**Comment by Dieterbe** [comment]
yeah. thanks. the http 500 was a good progress and things were actually working, just needed to update tsdb-gw and graphite-metrictank containers
