### ISSUE TITLE
why is the publicTest collector disabled by default?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#9]
just curious.
once the stack is up and running, it's obvious how to get started, adding an endpoint etc.
but it was a bit surprising when i stumbled on the collector overview that it was disabled by default.
any harm in enabling by default?

**Comment by Dieterbe** [comment]
actually i re-ran the devstack and left the collector disabled, and it all seems to work fine.
what is disabled then?

**Comment by woodsaj** [comment]
that is a good question.  The 'enabed' field was added to the collector model, but it is not used yet.  i have opened a couple of other issues for this.
issue https://github.com/raintank/grafana/issues/67 to track the enabled field not doing anything
issue  https://github.com/raintank/raintank-collector/issues/5 so collectors set 'enabled' to true when they create a new collector.
